[package]
name = "ultron-app"
version = "0.2.6"
edition = "2021"
description = "Ultron editor variant exposed as a web application"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-web"
readme = "../../README.md"
keywords = ["web", "editor", "monospace"]

[lib]
crate-type = ["rlib","cdylib"]


[dependencies]
ultron-web = { path = "../ultron-web" }
log = "0.4"
console_log = { version = "0.2", features = ["color"]}
console_error_panic_hook = "0.1"
async-trait = "0.1.58"
