[workspace]
members = [
    "packages/ultron",
    "packages/ultron-ssg",
    "packages/ultron-web",
    "packages/syntaxes-themes",
]

[patch.crates-io]
sauron = { path = "../sauron", default-features = false }

