cargo-features = ["strip"]

[workspace]
resolver = "2"
members = [
    "crates/syntaxes-themes",
    "crates/ultron-core",
    "crates/ultron-web",
    "crates/ultron-ssg",
    "crates/ultron-app",
    "examples/simple",
    "examples/rusty-usage",
]


[profile.release]
opt-level = 3 
lto = true
panic = "unwind"
strip = true

[profile.dev]
debug = 2
panic = "unwind"
strip = "none"

