[package]
name = "ultron"
version = "0.1.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"
description = "Ultron is a code editor written in rust"

[lib]
crate-type = ["rlib","cdylib"]

[dependencies]
sauron = { version = "0.43", features = [] }
log = "0.4"
unicode-width = "0.1"
percent-encoding = "2.1.0"
syntect = { version = "4", default-features = false, features = ["default-fancy"] }
css-colors = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = { version = "0.2", features = ["color"]}
console_error_panic_hook = "0.1"
wee_alloc = { version = "0.4", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pretty_env_logger = "0.4.0"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window", 
    "Navigator", 
    "Clipboard", 
    "DataTransfer", 
    "HtmlDocument",
    "DomRect",
    "Element",
]


[features]
default = ["standalone", "with-navigator-clipboard"]
with-navigator-clipboard = [] # use this feature if only want to support latest browsers
standalone = [] # run the ultron editor as a standalone web app
