cargo-features = ["strip"]

[workspace]
members = [
    "packages/ultron-core",
    #"packages/ultron",
    "packages/ultron-ssg",
    "packages/ultron-web",
    "packages/syntaxes-themes",
]

[patch.crates-io]

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
strip = true  
