[package]
name = "ultron"
version = "0.1.1"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"
description = "A web base text-editor with strong focus on displaying multi-width characters correctly"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron"
readme = "../../README.md"
keywords = ["web", "editor", "monospace"]

[dependencies]
sauron = { version = "0.43", path = "../../../sauron", default-features = false }
ultron-syntaxes-themes = { path = "../syntaxes-themes" }
log = "0.4"
unicode-width = "0.1"
css-colors = "1"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "Navigator",
    "Clipboard",
    "DataTransfer",
    "HtmlDocument",
    "DomRect",
    "Element",
]


[features]
default = ["with-navigator-clipboard", "with-dom"]
with-navigator-clipboard = [] # use this feature if only want to support latest browsers
with-dom = ["sauron/with-dom", "sauron/with-node-macro", "sauron/with-request-animation-frame"]
