[package]
name = "ultron-ssg"
version = "0.2.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"
description = "A syntax highlighting library ideal for usage in a static site generator"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-ssg"
readme = "../../README.md"
keywords = ["syntax", "highlighting", "monospace"]

[dependencies]
ultron = { version = "0.2.0", path = "../ultron" , default-features = false}

