[package]
name = "ultron-ssg"
version = "0.2.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"
description = "A syntax highlighting library ideal for usage in a static site generator"

[dependencies]
pretty_env_logger = "0.4.0"
ultron = { path = "../ultron" , default-features = false}
