[package]
name = "ultron-ssg"
version = "0.4.0"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2021"
description = "A syntax highlighting library ideal for usage in a static site generator"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-ssg"
readme = "../../README.md"
keywords = ["syntax", "highlighting", "monospace"]

[dependencies]
sauron = { path = "../../../sauron" }
#sauron = "0.59"
ultron-syntaxes-themes = { path = "../syntaxes-themes" }
css-colors = "1"
