[package]
name = "rusty-usage"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.19"
ultron-web = { path = "../../packages/ultron-web", features = ["custom_element"] }
