[package]
name = "ultron-syntaxes-themes"
version = "0.2.3"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
edition = "2018"
description = "Syntaxes and themes dump for ultron"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-syntaxes-themes"
readme = "../../README.md"
keywords = ["syntax", "themes", "highlighting"]

[dependencies]
syntect = { version = "4", default-features = false, features = ["default-fancy"] }
once_cell = "1"
log = "0.4"
