[package]
name = "simple"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ultron-web = { path = "../../packages/ultron-web", features = ["custom_element"] }

