[package]
name = "ultron-web"
version = "0.3.0"
edition = "2021"
description = "Ultron editor variant exposed as a web application"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-web"
readme = "../../README.md"
keywords = ["web", "editor", "monospace"]



[lib]
crate-type = ["rlib","cdylib"]


[dependencies]
ultron-core = { version = "0.3.0", path = "../ultron-core", features = ["callback"] }
sauron = "0.55.0"
#sauron = { path = "../../../sauron"}
log = "0.4"
console_log = { version = "0.2", features = ["color"]}
console_error_panic_hook = "0.1"
css-colors = "1"
async-trait = "0.1.58"
serde-wasm-bindgen = "0.5.0"

[dev-dependencies]
ropey = "1.6.0"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "Navigator",
    "Clipboard",
    "DataTransfer",
    "HtmlDocument",
    "DomRect",
    "Element",
]


[features]
default = ["with-navigator-clipboard", "with-measure", "with-ric", "with-raf", "with-interning"]
with-ric = ["sauron/with-ric"]
with-raf = ["sauron/with-raf"]
with-measure = ["sauron/with-measure"]
with-debug = ["sauron/with-debug"]
with-interning = ["sauron/with-interning"]
with-navigator-clipboard = [] # use this feature if only want to support latest browsers
