[package]
name = "ultron-web"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib","cdylib"]

[dependencies]
ultron = { path = "../ultron" }
log = "0.4"
console_log = { version = "0.2", features = ["color"]}
console_error_panic_hook = "0.1"
wee_alloc = { version = "0.4", optional = true }
