[package]
name = "ultron-web"
version = "0.2.6"
edition = "2018"
description = "Ultron editor variant exposed as a web application"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-web"
readme = "../../README.md"
keywords = ["web", "editor", "monospace"]

[lib]
crate-type = ["rlib","cdylib"]


[dependencies]
ultron = { version = "0.2.6", path = "../ultron", features = ["with-measure"] }
log = "0.4"
console_log = { version = "0.2", features = ["color"]}
console_error_panic_hook = "0.1"
wee_alloc = { version = "0.4", optional = true }

