[package]
name = "ultron-web"
version = "0.2.6"
edition = "2021"
description = "Ultron editor variant exposed as a web application"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-web"
readme = "../../README.md"
keywords = ["web", "editor", "monospace"]

[lib]
crate-type = ["rlib","cdylib"]


[dependencies]
ultron-core = { path = "../ultron-core" }
sauron = { path = "../../../sauron" }
log = "0.4"
console_log = { version = "0.2", features = ["color"]}
console_error_panic_hook = "0.1"
css-colors = "1"
async-trait = "0.1.58"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "Navigator",
    "Clipboard",
    "DataTransfer",
    "HtmlDocument",
    "DomRect",
    "Element",
]


[features]
default = ["with-navigator-clipboard"]
with-navigator-clipboard = [] # use this feature if only want to support latest browsers
