[package]
name = "ultron-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-width = "0.1"
nalgebra = "0.29.0"
log = "0.4.17"
