[package]
name = "ultron-core"
version = "0.4.0"
edition = "2021"
description = "The core component of ultron editor"
license = "MIT"
repository = "https://github.com/ivanceras/ultron"
documentation = "https://docs.rs/ultron-core"
readme = "../../README.md"
keywords = ["web", "editor", "monospace"]


[dependencies]
unicode-width = "0.1"
nalgebra = "0.32.2"
log = "0.4.17"
ultron-syntaxes-themes = { version = "0.4.0", path = "../syntaxes-themes" }
async-recursion = "1.0.4"

[features]
callback = []
