name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install stable
      run: rustup toolchain install stable

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build
      run: cargo build --all

    - name: Run tests
      run: cargo test --all

    - name: Build wasmp
      run: wasm-pack build --target web
