name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install stable
      run: rustup toolchain install stable

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build with all features
      run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --all --all-features

    - name: Build
      run: ./build.sh

    - name: Run tests
      run: ./test.sh

    - name: Build wasmp
      run: RUSTFLAGS=--cfg=web_sys_unstable_apis wasm-pack build packages/ultron-web --target web
