name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install stable
      run: rustup toolchain install stable

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build no features
      run: cargo build --all --no-default-features

    - name: Build with all features
      run: cargo build --all --all-features

    - name: Build
      run: ./build.sh

    - name: Run tests
      run: ./test.sh

    - name: Build wasmp
      run: wasm-pack build packages/ultron-web --target web
