name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ivanceras/sauron
        path: './sauron'

    - uses: actions/checkout@v2
      with:
        repository: ivanceras/ultron
        path: './ultron'

    - name: Install stable
      run: rustup toolchain install stable

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build with all features
      run: cd ultron && RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --all --all-features

    - name: Build
      run: cd ultron && RUSTFLAGS=--cfg=web_sys_unstable_apis wasm-pack build packages/ultron-app --target web --release --features "with-navigator-clipboard with-measure with-ric with-raf"

    - name: Run tests
      run: cd ultron && cargo test --all

    - name: Build wasmp
      run: cd ultron && RUSTFLAGS=--cfg=web_sys_unstable_apis wasm-pack build packages/ultron-web --target web
